name = "listadepreciosseidor"
main = "src/worker.js"
compatibility_date = "2026-01-01"

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[kv_namespaces]]
binding = "PM_KV"
id = "64aaa5613ef240b486f24e02610498cd"

[[r2_buckets]]
binding = "DOCS_BUCKET"
bucket_name = "presalesmx-docs"

[triggers]
crons = ["0 22 * * 5"]
